// export const RootUrl = "http://192.168.0.104:3005";

export const authTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  LOGOUT_USER: "LOGOUT_USER",
};

export const productTypes = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",

  CREATE_PRODUCT: "CREATE_PRODUCT",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  TOGGLE_EXPIRE: "TOGGLE_EXPIRE",
  TOGGLE_EXPIRE_SUCCESS: "TOGGLE_EXPIRE_SUCCESS",
  TOGGLE_EXPIRE_FAIL: "TOGGLE_EXPIRE_FAIL",
};

export const platformTypes = {
  GET_ALL_PLATFORMS: "GET_ALL_PLATFORMS",
  GET_ALL_PLATFORMS_SUCCESS: "GET_ALL_PLATFORMS_SUCCESS",
  GET_ALL_PLATFORMS_FAIL: "GET_ALL_PLATFORMS_FAIL",

  CREATE_PLATFORM: "CREATE_PLATFORM",
  CREATE_PLATFORM_SUCCESS: "CREATE_PLATFORM_SUCCESS",
  CREATE_PLATFORM_FAIL: "CREATE_PLATFORM_FAIL",

  UPDATE_PLATFORM: "UPDATE_PLATFORM",
  UPDATE_PLATFORM_SUCCESS: "UPDATE_PLATFORM_SUCCESS",
  UPDATE_PLATFORM_FAIL: "UPDATE_PLATFORM_FAIL",

  DELETE_PLATFORM: "DELETE_PLATFORM",
  DELETE_PLATFORM_SUCCESS: "DELETE_PLATFORM_SUCCESS",
  DELETE_PLATFORM_FAIL: "DELETE_PLATFORM_FAIL",
};

export const offerTypes = {
  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  GET_ALL_OFFERS_SUCCESS: "GET_ALL_OFFERS_SUCCESS",
  GET_ALL_OFFERS_FAIL: "GET_ALL_OFFERS_FAIL",

  CREATE_OFFER: "CREATE_OFFER",
  CREATE_OFFER_SUCCESS: "CREATE_OFFER_SUCCESS",
  CREATE_OFFER_FAIL: "CREATE_OFFER_FAIL",

  UPDATE_OFFER: "UPDATE_OFFER",
  UPDATE_OFFER_SUCCESS: "UPDATE_OFFER_SUCCESS",
  UPDATE_OFFER_FAIL: "UPDATE_OFFER_FAIL",

  DELETE_OFFER: "DELETE_OFFER",
  DELETE_OFFER_SUCCESS: "DELETE_OFFER_SUCCESS",
  DELETE_OFFER_FAIL: "DELETE_OFFER_FAIL",
};


export const userTypes = {
  GET_USER_DETAILS: "GET_USER_DETAILS",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",

  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  GET_BUSINESS_DETAILS: "GET_BUSINESS_DETAILS",
  GET_BUSINESS_DETAILS_SUCCESS: "GET_BUSINESS_DETAILS_SUCCESS",
  GET_BUSINESS_DETAILS_FAIL: "GET_BUSINESS_DETAILS_FAIL",

  CREATE_BUSINESS: "CREATE_BUSINESS",
  CREATE_BUSINESS_SUCCESS: "CREATE_BUSINESS_SUCCESS",
  CREATE_BUSINESS_FAIL: "CREATE_BUSINESS_FAIL",

  DELETE_BUSINESS: "DELETE_BUSINESS",
  DELETE_BUSINESS_SUCCESS: "DELETE_BUSINESS_SUCCESS",
  DELETE_BUSINESS_FAIL: "DELETE_BUSINESS_FAIL",

  UPDATE_BUSINESS: "UPDATE_BUSINESS",
  UPDATE_BUSINESS_SUCCESS: "UPDATE_BUSINESS_SUCCESS",
  UPDATE_BUSINESS_FAIL: "UPDATE_BUSINESS_FAIL",
};

export const categoryTypes = {
  GET_CATEGORIES_DETAILS: "GET_CATEGORIES_DETAILS",
  GET_CATEGORIES_DETAILS_SUCCESS: "GET_CATEGORIES_DETAILS_SUCCESS",
  GET_CATEGORIES_DETAILS_FAIL: "GET_CATEGORIES_DETAILS_FAIL",

  CREATE_CATEGORIES: "CREATE_CATEGORIES",
  CREATE_CATEGORIES_SUCCESS: "CREATE_CATEGORIES_SUCCESS",
  CREATE_CATEGORIES_FAIL: "CREATE_CATEGORIES_FAIL",

  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAIL: "UPDATE_CATEGORIES_FAIL",

  GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAIL: "GET_ALL_CATEGORIES_FAIL",

  DELETE_CATEGORIES: "DELETE_CATEGORIES",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAIL: "DELETE_CATEGORIES_FAIL",
  CLOSE_MODAL: "CLOSE_MODAL",
};

export const utilTypes = {
  GET_ALL_THEMES: "GET_ALL_THEMES",
  GET_ALL_THEMES_SUCCESS: "GET_ALL_THEMES_SUCCESS",
  GET_ALL_THEMES_FAIL: "GET_ALL_THEMES_FAIL",

  ADD_NEW_THEME: "ADD_NEW_THEME",
  ADD_NEW_THEME_SUCCESS: "ADD_NEW_THEME_SUCCESS",
  ADD_NEW_THEME_FAIL: "ADD_NEW_THEME_FAIL",

  REMOVE_THEME: "REMOVE_THEME",
  REMOVE_THEME_SUCCESS: "REMOVE_THEME_SUCCESS",
  REMOVE_THEME_FAIL: "REMOVE_THEME_FAIL",

  UPDATE_THEME: "UPDATE_THEME",
  UPDATE_THEME_SUCCESS: "UPDATE_THEME_SUCCESS",
  UPDATE_THEME_FAIL: "UPDATE_THEME_FAIL",
};
